SET
SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET
time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE TABLE `pixels`
(
    `id`       int NOT NULL,
    `x`        int NOT NULL,
    `y`        int NOT NULL,
    `z`        int NOT NULL,
    `todelete` int DEFAULT NULL,
    `level`    int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE `pixels`
    ADD PRIMARY KEY (`id`);

ALTER TABLE `pixels`
    MODIFY `id` int NOT NULL AUTO_INCREMENT;
COMMIT;